using ActivusX.Shared.Helpers;

namespace ActivusX.Shared.Models.System.Enums;

public enum AXUserAccountRole
{
    // super user (not available, generated by system only)
    [StringValue("Super User")]
    sudo,

    [StringValue("Administrator")]
    Administrator,

    [StringValue("Power User")]
    PowerUser,

    [StringValue("HR Administrator")]
    HRAdministrator,

    [StringValue("IT Support")]
    ITSupport,

    [StringValue("Group Manager")]
    GroupManager,

    [StringValue("User")]
    User,

    [StringValue("Service Account")]
    ServiceAccount,

    [StringValue("API Account")]
    ApiAccount,

    [StringValue("Auditor")]
    Auditor,

    [StringValue("Guest User")]
    Guest
}
