@ActivusX.API_HostAddress = http://localhost:5253

GET {{ActivusX.API_HostAddress}}/todos/
Accept: application/json

###

GET {{ActivusX.API_HostAddress}}/todos/1
Accept: application/json

###
